/**
 * Encounter Generator — player-facing copy (German).
 */

export const ENCOUNTER_GENERATOR_COPY = {
  title: 'Encounter-Generator',
  progress: (step: number, total: number) => `Schritt ${step} von ${total}`,

  party: {
    heading: 'Wer nimmt am Encounter teil?',
    body: 'Waehle die Charaktere, die als Gruppe gegen den Encounter antreten. Aus ihren Werten (HP, Ausweichen, Ruestung, Angriffspool, Schaden) wird der Gegner berechnet.',
    empty: 'Keine Charaktere gefunden. Lege zuerst Charakter-Actors an.',
    selected: (n: number) => `${n} ausgewaehlt`,
    metricsHeading: 'Gruppen-Kennwerte',
  },

  difficulty: {
    heading: 'Wie hart soll der Encounter sein?',
    body: 'Steuert Kampfdauer (Boss-HP), Trefferchancen und wie hart Boss-Treffer einschlagen.',
    moderate: {
      title: 'Moderat',
      body: 'Kuerzerer Kampf (~4 Runden Boss). Gruppe trifft oft, Boss-Treffer tun ~20% der HP weh.',
    },
    hard: {
      title: 'Hart (Souls-like)',
      body: 'Langer Kampf (~6 Runden Boss). Gruppe trifft ~65%, Boss-Treffer ~32% der HP. Fehler sind teuer.',
    },
    brutal: {
      title: 'Brutal',
      body: 'Sehr langer Kampf (~8 Runden Boss). Gruppe trifft ~58%, Boss-Treffer ~45% der HP. Unverzeihlich.',
    },
  },

  composition: {
    heading: 'Zusammensetzung des Encounters',
    body: 'Lege fest, aus wie vielen Bossen und Minions der Encounter besteht.',
    bossCount: 'Anzahl Bosse',
    phasesPerBoss: 'Phasen pro Boss',
    minionCount: 'Minions pro Welle',
    respawnCadence: 'Minion-Respawn',
    cadenceNone: 'Kein Respawn',
    cadenceEvery: (n: number) => (n === 1 ? 'Jede Runde' : `Alle ${n} Runden`),
    respawnNote: 'Bosse bleiben bis zum Sieg. Minions tauchen im gewaehlten Takt wieder auf (Empfehlung im naechsten Schritt).',
  },

  review: {
    heading: 'Vorschlag pruefen & anpassen',
    body: 'HP, Rüstung, Ausweichen, Angriffswürfel und Reaktionen sind editierbar. Mehrere gleiche Hauptgegner entstehen als Kopien; unterschiedliche Kits siehst du als eigene Blöcke.',
    kitHeading: 'Hauptgegner-Kits',
    kitName: 'Name',
    copies: (n: number) => `${n}× identisch erzeugen`,
    reactionsHeading: 'Reaktionen',
    bossesHeading: 'Bosse',
    minionsHeading: 'Minions',
    respawnHeading: 'Respawn-Empfehlung',
    recommend: (perWave: number, cadence: number) =>
      cadence > 0
        ? `Empfehlung: ${perWave} Minions ${cadence === 1 ? 'jede Runde' : `alle ${cadence} Runden`}.`
        : 'Empfehlung: kein Respawn noetig.',
    col: {
      name: 'Name',
      phase: 'Phase',
      hp: 'HP',
      evade: 'Ausweichen',
      armor: 'Ruestung',
      attackDice: 'Angriffs-W8',
      damageDice: 'Schadens-W8',
      slots: 'Angriffe/Runde',
      mr: 'MR',
    },
    note: 'Hinweis: Ausweichen wird in-engine aus MR und Beweglichkeit erzeugt; Ruestung entspricht der MR. Phasen-Wechsel steuerst du im NSC-Bogen (aktive Phase).',
  },

  name: {
    heading: 'Encounter-Projekt benennen & erzeugen',
    body: 'Es entsteht ein Encounter-Projekt: ein Ordner mit Unterordnern (Boss, ggf. Adds und Encounter Mechanics), die fertigen NSC-Actors sowie ein Journal mit Encounter Summary, Threat Report und druckbarem NPC-Sheet.',
    label: 'Encounter-Name',
    placeholder: 'z.B. The Red Priest',
  },

  concept: {
    heading: 'Kampfidee definieren',
    body: 'Du legst fest, wie viele Hauptgegner es gibt, was sie tun und welche Werte sie haben. Der Generator füllt den Rest — du siehst HP, Rüstung und Schaden hier schon und kannst sie überschreiben.',
    preset: 'Archetyp-Vorlage',
    presetHint: 'Fertige Boss-Ideen zum Starten. „Eigenes Konzept“ lässt alle Felder frei.',
    presetNone: 'Eigenes Konzept',
    groupHeading: 'Hauptgegner',
    bossCount: 'Anzahl Hauptgegner',
    bossCountHint: '1–6 Gegner, die gegen die Gruppe stehen. 3 gleiche Zweihand-Kämpfer sind z. B. 3.',
    kitMode: 'Kits',
    kitModeHint: '„Alle gleich“ kopiert ein Kit. „Unterschiedlich“ lässt dich danach jeden einzeln anpassen.',
    loadoutHeading: 'Angriffe & Waffen',
    weaponProfile: 'Waffe',
    weaponProfileHint: 'Einhand, Zweihand (2 m, mehr Schaden) oder Fernkampf.',
    attackShape: 'Angriffe pro Runde',
    attackShapeHint: 'Schnell „1 Einzel + 1 Fläche“ wählen — oder Aktionen und Zielmuster frei lassen.',
    baseDamage: 'Basis-Schaden (W8)',
    baseDamageHint: '0 = Generator. Sonst jeder Waffen-/Zauber-Angriff nutzt genau so viele explodierende W8.',
    valuesHeading: 'Werte vorher sehen / überschreiben',
    valuesHint: '0 = automatisch aus der Gruppe. Gesetzte Werte gelten pro Hauptgegner. Kampf-Rüstung ist die MR.',
    hpOverride: 'HP',
    armorOverride: 'Rüstung / MR',
    evadeOverride: 'Ausweichen',
    reactionsHeading: 'Reaktionen (1–2)',
    reactionsBody: 'Leer lassen oder Standard-Manöver / eigenen Namen wählen. Stehen auf jedem erzeugten Hauptgegner.',
    reactionN: (n: number) => `Reaktion ${n}`,
    previewHeading: 'Vorschau pro Hauptgegner',
    previewNote: 'Im Schritt „Prüfen“ kannst du Würfel, HP und Reaktionen noch ändern.',
    previewNone: 'Wähle zuerst die Gruppe, dann erscheinen hier die berechneten Werte.',
    rank: 'Enemy Rank / Importance',
    rankHint: 'Wie wichtig/schwer der Encounter ist — steuert Budget, Dauer und Druck auf die Gruppe.',
    style: 'Primary Combat Style',
    styleHint: 'Hauptart, wie der Boss kämpft (Zauber, Martial, Hybrid, Summoner oder Umgebung).',
    primarySpecial: 'Primary Special',
    primarySpecialHint: 'Das zentrale Diminishing Special, das der Boss im Kampf aufbaut und drückt.',
    secondaryStyle: 'Secondary Style (optional)',
    secondaryStyleHint: 'Optionaler Zweitstil für Abwechslung im Power-Cycle.',
    actions: 'Aktionen pro Runde',
    actionsHint: 'Wie viele Angriffs-/Power-Aktionen der Boss pro Runde bekommt.',
    targeting: 'Zielmuster',
    targetingHint: 'Ob der Boss Einzelziele, Flächen oder beides bevorzugt.',
    phases: 'Anzahl Phasen',
    phasesHint: 'Boss-Phasen (HP-Bars / Verhaltenswechsel). Mehr Phasen = längerer, gestufter Kampf.',
    cycleLength: 'Power-Cycle Länge',
    cycleLengthHint: 'Wie viele verschiedene Powers im rotierenden Cycle liegen.',
    cycleStyle: 'Cycle-Stil',
    cycleStyleHint: 'Wie der Generator die Reihenfolge der Boss-Powers bestimmt.',
    envActions: 'Umgebungs-Aktionen pro Runde',
    envActionsHint: 'Nur bei Environmental: wie oft die Umgebung pro Runde zuschlägt.',
  },

  adds: {
    heading: 'Adds (Verstärkung)',
    body: 'Adds sind keine „bisschen Health“ — jeder Add erzeugt jede weitere Runde neue Aktionen. Der Generator rechnet: Add Threat = erwartete Aktionen bis zum Tod × Bedrohung pro Aktion.',
    enabled: 'Adds verwenden',
    enabledHint: 'Schaltet Verstärkung hinzu. Adds teilen sich das Encounter-Budget mit dem Boss.',
    durability: 'Add Durability',
    durabilityHint: 'Wie lange ein einzelner Add überlebt — steuert HP/Zähigkeit der Adds.',
    durabilityOptions: {
      minion: 'Minion — stirbt an einem erfolgreichen Angriff',
      light: 'Light — überlebt einen schwachen Treffer',
      standard: 'Standard — überlebt ca. zwei Angriffe',
      elite: 'Elite — braucht gezielten Fokus',
    },
    durabilityHints: {
      minion: 'Sehr fragil: ein sauberer Treffer reicht. Gut für Mengendruck.',
      light: 'Übersteht einen schwachen Hit — kurze Lebensdauer, aber nicht sofort weg.',
      standard: 'Braucht etwa zwei Angriffe — spürbarer Fokus-Trade.',
      elite: 'Muss bewusst fokussiert werden — teure Adds, hoher Einzeldruck.',
    },
    pressure: 'Add Pressure',
    pressureHint: 'Wie gefährlich die Adds sind, wenn sie leben und handeln dürfen.',
    pressureOptions: {
      harassment: 'Harassment — einzeln nahezu irrelevant',
      noticeable: 'Noticeable — ~½ Health Level pro Runde',
      dangerous: 'Dangerous in Groups — ~1 Health Level pro Runde',
      lethal: 'Lethal if Ignored — volle Population schaltet einen Charakter in 2 Runden aus',
    },
    pressureHints: {
      harassment: 'Einzeln kaum relevant — Druck entsteht erst durch Menge und Zeit.',
      noticeable: 'Spürbarer Chip-Schaden (~½ Health Level pro Runde bei Zielpopulation).',
      dangerous: 'Gruppen von Adds kosten ~1 Health Level pro Runde — Ignorieren tut weh.',
      lethal: 'Volle Population killt/ausschaltet einen Charakter in ca. 2 Runden.',
    },
    targetActive: 'Ziel-Population (gleichzeitig aktiv)',
    targetActiveHint: 'Wie viele Adds idealerweise gleichzeitig auf dem Feld sein sollen.',
    maxActive: 'Maximum aktiv (0 = automatisch)',
    maxActiveHint: 'Harte Obergrenze gleichzeitiger Adds. 0 = Generator wählt automatisch.',
    spawnPerRound: 'Spawn-Rate (pro Runde)',
    spawnPerRoundHint: 'Wie viele neue Adds pro Spawn-Tick erscheinen (je nach Muster).',
    spawnPattern: 'Spawn-Muster',
    spawnPatternHint: 'Wann Adds erscheinen — kontinuierlich, Burst, Phasenstart oder Trigger.',
    spawnPatternOptions: {
      continuous: 'Continuous — jede Runde',
      burst: 'Burst — alle zu Beginn',
      'phase-start': 'Phase Start — bei Phasenwechsel',
      triggered: 'Triggered — durch Ereignis',
    },
    spawnPatternHints: {
      continuous: 'Gleichmäßiger Nachschub jede Runde.',
      burst: 'Viele Adds sofort — dann weniger oder kein Nachzug.',
      'phase-start': 'Neue Welle, wenn der Boss die Phase wechselt.',
      triggered: 'Spawn an ein Ereignis gekoppelt (z. B. Boss-Aktion / Threshold).',
    },
    summonCost: 'Beschwören kostet den Boss eine Aktion',
    summonCostHint: 'Wenn aktiv, muss der Boss eine Aktion fürs Spawnen opfern — weniger eigene Offensive.',
    disabledNote: 'Ohne Adds bekommt der Boss das volle Encounter-Budget.',
  },

  threat: {
    heading: 'Threat Report',
    hitChances: 'Trefferchance (niedrig / Ø / hoch Ausweichen)',
    aoeHitChance: 'AoE-Trefferchance (pro Kreatur vs Ø Ausweichen)',
    rawDamage: 'Erwarteter Schaden pro Treffer (vor Rüstung)',
    afterArmor: 'Nach Ø Rüstung/DR',
    persistent: 'Persistenter Schaden pro Runde (ignoriert Rüstung)',
    burst: 'Max. Runde-1-Burst auf ein Ziel',
    groupDamage: 'Erwarteter Gruppenschaden pro Runde',
    envDamage: 'Umgebungs-/Zonenschaden pro Runde',
    actions: 'Gegnerische Aktionen R1→R5 (inkl. Adds)',
    duration: 'Erwartete Kampfdauer',
    healthLevels: (n: number) => `≈ ${n} Health Levels`,
    hlSize: 'Ø Health-Level-Größe der Gruppe',
    round1Lowest: 'Runde-1-Verlust des zerbrechlichsten Charakters',
    warningsHeading: 'Balancing-Warnungen',
    noWarnings: 'Keine Warnungen — das Konzept sieht spielbar aus.',
    cycleHeading: 'Power Cycle',
    addsHeading: 'Adds',
    envHeading: 'Umgebungsmechanik',
    phaseChangesLabel: 'Änderungen',
  },

  nav: {
    back: 'Zurueck',
    next: 'Weiter',
    generate: 'Erzeugen',
  },

  notify: {
    noParty: 'Bitte waehle mindestens einen Charakter aus.',
    noName: 'Bitte gib einen Namen fuer den Encounter ein.',
    gmOnly: 'Nur der Spielleiter kann Encounter erzeugen.',
    done: (folder: string, count: number) => `Encounter "${folder}" erzeugt (${count} Actors).`,
    failed: 'Encounter konnte nicht erzeugt werden - siehe Konsole.',
  },
} as const;
